---
- name: Test easy-rsa installation
  hosts: ca_server
  gather_facts: false
  become: true
  roles:
    - ca_server

- name: Test VPN server installation
  hosts: ca_server
  gather_facts: false
  become: true
  roles:
    - vpn_server

- name: Test Prometheus installation
  hosts: monitoring_server
  gather_facts: false
  become: true
  roles:
    - prometheus
  
- name: Test Node Exporter installation
  hosts: all_infra
  gather_facts: false
  become: true
  roles:
    - node-exporter
